services:
    laravel.app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: laravel-docker-app
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    nginx:
        image: nginx:latest
        ports:
            - '4005:80'
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel.app
        networks:
            - laravel

    node:
        image: node:23
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - '5175:5175'
        command: sh -c "npm install && npm run dev"
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - '3307:3306'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
